services:
  db:
    image: 'mysql:8.4'
    restart: 'always'
    command: --mysql-native-password=ON
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      - '3306'